### ISSUE TITLE
Still getting a warning about using Node 6 execution handler

### ISSUE THREAD

**Issue by praneetloke** [shayki5/azure-devops-get-revision-task#7]
Despite having updated the [execution target](https://github.com/shayki5/azure-devops-get-revision-task/pull/6/files#diff-e6eec45c9860116ef4156139f7020ab15fec4ccdcd12d6512b6c97ba656d2baeR27) in PR #6 I am still seeing a warning about the task using the deprecated Node 6 execution handler. I am not sure why that is. I have a suspicion it's because the [task's version is not updated](https://github.com/shayki5/azure-devops-get-revision-task/blob/master/azure-pipelines.yml#L48) with every release and instead only the extension version is updated? I do see that Azure DevOps shows that the extension version is `1.0.20`, however, the task version is still at `1.0.0`. I am not 100% sure what's wrong here.

The warning I get is:

> ##[warning]This task uses Node 6 execution handler, which will be removed March 31st 2022. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10 (check this page also if you would like to disable Node 6 deprecation warnings). If you are the user - feel free to reach out to the owners of this task to proceed on migration.

**Comment by shayki5** [comment]
Hi, yea, very strange, it looks like you fix it in your PR.
Is not related to the `updateTasksVersion: false` because I bumped the version in another way and as you said, the version now is `1.0.20`.

**Comment by praneetloke** [comment]
Closing this since I don't see the warnings anymore. Not since December 6 but until then I was getting the warnings despite my PR having been merged at the end of November. 🤷‍♂️
